name: Daily Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC daily
  workflow_dispatch:      # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30   # Increase timeout for complex dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'    # Cache dependencies for faster runs

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx xvfb  # Required for PyQt5/GUI tests

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt  # If you have one
          pip install pytest pytest-cov pytest-xdist pytest-html
          pip install PyQt5 pytest-qt   # Core GUI testing deps
          pip install opencv-python pandas numpy scikit-learn  # Key ML deps
          pip install tensorflow torch  # Deep learning frameworks
          # Install remaining packages (grouped for efficiency)
          pip install \
            requests flask flask-cors \
            matplotlib seaborn plotly \
            pymongo motor \
            langchain transformers \
            ultralytics mediapipe \
            pytest-xdist  # Parallel test execution

      - name: Run tests with Xvfb (for GUI tests)
        run: |
          xvfb-run pytest tests/ \
            --cov=. \
            --cov-report=xml \
            --cov-report=html \
            --junitxml=test-results/results.xml \
            -n auto  # Parallel tests using all cores

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports
          path: |
            htmlcov/
            test-results/
            coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: success()