name: Daily Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC daily
  workflow_dispatch:      # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx xvfb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask PyQt5 requests pytest pytest-qt

      - name: Run tests with Xvfb
        run: |
          xvfb-run pytest tests/ --cov=.
