name: Daily Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Latest Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Gets full history (useful for future Git features)

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1 \
            xvfb \
            python3-dev

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install \
            flask \
            flask-cors \
            PyQt5 \
            requests \
            pytest \
            pytest-qt \
            pandas \
            scikit-learn \
            matplotlib \
            seaborn

      - name: Run Pytest with Coverage
        run: |
          pytest --cov=. --cov-report=xml --cov-report=html

      - name: Save Coverage to DevOps Branch
        env:
          TOKEN: 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
        run: |
          # Configure Git user
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Check if coverage files exist and copy them
          if [ -d "htmlcov" ] && [ -f "coverage.xml" ]; then
            mkdir -p temp_coverage
            cp -r htmlcov temp_coverage/htmlcov
            cp coverage.xml temp_coverage/
          else
            echo "No coverage files found, skipping commit."
            exit 0
          fi

          # Prepare git commit
          git fetch origin
          git checkout -B devops || git checkout -b devops

          # Remove old coverage files and move the new ones
          rm -rf htmlcov coverage.xml
          mv temp_coverage/htmlcov .
          mv temp_coverage/coverage.xml .

          # Commit and push
          git add htmlcov coverage.xml
          git commit -m "Daily Coverage Report - $(date -u '+%Y-%m-%d')" || echo "No changes to commit"

          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin devops
