name: Daily Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1 \
            xvfb \
            python3-dev

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          # Install only essential packages first
          pip install flask PyQt5 requests pytest pytest-qt flask-cors
          
          # If you really need the other packages, install them separately
          # with relaxed version constraints
          pip install \
            pandas \
            scikit-learn \
            matplotlib \
            seaborn \
            --no-deps  # Skip dependency resolution for these

      - name: Run tests
        run: |
          xvfb-run pytest tests/
